template:
  colors:
    primary: "#000000"
    secondary: "#888888"
    accent: "#4A86E8"
  fonts:
    main: "Helvetica"
    accent: "Helvetica-Bold"
  font_sizes:
    title: 20
    invoice_number: 14
    section_header: 10
    normal_text: 9
  layout:
    page_size: "A4"
    margin_top: 0.3
    margin_right: 0.5
    margin_bottom: 0.5
    margin_left: 0.5