"""Refactor backend for async db operations

Revision ID: 3375f44eba3e
Revises: a9008bba5c8f
Create Date: 2024-09-18 12:31:27.070461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3375f44eba3e'
down_revision: Union[str, None] = 'a9008bba5c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('templates', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('templates', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('templates', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_templates_is_deleted'), 'templates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_templates_user_id'), 'templates', ['user_id'], unique=False)
    op.create_index('ix_templates_user_id_is_default', 'templates', ['user_id', 'is_default'], unique=False)
    op.alter_column('templates', 'is_deleted', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_templates_user_id_is_default', table_name='templates')
    op.drop_index(op.f('ix_templates_user_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_is_deleted'), table_name='templates')
    op.drop_column('templates', 'deleted_at')
    op.drop_column('templates', 'is_deleted')
    op.drop_column('templates', 'updated_at')
    op.drop_column('templates', 'created_at')
    # ### end Alembic commands ###
