"""Update contact model

Revision ID: 4ddec9156356
Revises: e628c8b8733a
Create Date: 2024-08-29 16:17:26.195222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddec9156356'
down_revision: Union[str, None] = 'e628c8b8733a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('company', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('address', sa.String(), nullable=True))
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.drop_column('contacts', 'address1')
    op.drop_column('contacts', 'address2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('address2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('address1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=True)
    op.drop_column('contacts', 'address')
    op.drop_column('contacts', 'company')
    # ### end Alembic commands ###
