"""Enhance logging and exception handling for invoice and template creation

Revision ID: 604ad56f3048
Revises: 98dc8ccc3ff0
Create Date: 2024-08-31 15:18:54.208054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604ad56f3048'
down_revision: Union[str, None] = '98dc8ccc3ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
