"""Remove type field from and add created_at field to Contact model


Revision ID: 6d12c5d5bf1f
Revises: ec9512e66548
Create Date: 2024-09-11 09:04:50.256270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d12c5d5bf1f'
down_revision: Union[str, None] = 'ec9512e66548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('contacts', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'created_at')
    # ### end Alembic commands ###
