"""Refactor invoices, items, and subitems logic for increased efficiency

Revision ID: 6d25d077a44a
Revises: 6d12c5d5bf1f
Create Date: 2024-09-17 15:35:39.134238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d25d077a44a'
down_revision: Union[str, None] = '6d12c5d5bf1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_subitems_invoice_item_id'), 'invoice_subitems', ['invoice_item_id'], unique=False)
    op.add_column('invoices', sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('tax', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.create_index('ix_invoices_bill_to_id', 'invoices', ['bill_to_id'], unique=False)
    op.create_index('ix_invoices_invoice_date', 'invoices', ['invoice_date'], unique=False)
    op.create_index('ix_invoices_send_to_id', 'invoices', ['send_to_id'], unique=False)
    op.create_index(op.f('ix_invoices_template_id'), 'invoices', ['template_id'], unique=False)
    op.create_index('ix_invoices_total', 'invoices', ['total'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index('ix_invoices_total', table_name='invoices')
    op.drop_index(op.f('ix_invoices_template_id'), table_name='invoices')
    op.drop_index('ix_invoices_send_to_id', table_name='invoices')
    op.drop_index('ix_invoices_invoice_date', table_name='invoices')
    op.drop_index('ix_invoices_bill_to_id', table_name='invoices')
    op.drop_column('invoices', 'total')
    op.drop_column('invoices', 'tax')
    op.drop_column('invoices', 'subtotal')
    op.drop_index(op.f('ix_invoice_subitems_invoice_item_id'), table_name='invoice_subitems')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    # ### end Alembic commands ###
