"""Update invoice and template schemas, models, and services

Revision ID: 85f3bd0b1a5a
Revises: af2a8445e9b0
Create Date: 2024-08-31 14:01:01.426319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f3bd0b1a5a'
down_revision: Union[str, None] = 'af2a8445e9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
