"""Updated invoice naming conventions for clarity

Revision ID: 88ea364e42bb
Revises: 604ad56f3048
Create Date: 2024-08-31 15:49:05.970555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ea364e42bb'
down_revision: Union[str, None] = '604ad56f3048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('invoice_items', 'rate')
    op.add_column('invoices', sa.Column('invoice_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('override_total', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('invoices', 'date_of_service')
    op.drop_column('invoices', 'manual_total')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('manual_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('date_of_service', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('invoices', 'override_total')
    op.drop_column('invoices', 'invoice_date')
    op.add_column('invoice_items', sa.Column('rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('invoice_items', 'unit_price')
    # ### end Alembic commands ###
