"""Update models and schema to allow negative values

Revision ID: 8cc8395739e1
Revises: 58bb598e9c85
Create Date: 2024-09-01 10:42:24.619584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc8395739e1'
down_revision: Union[str, None] = '58bb598e9c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
