"""Refactor invoice updates to maintain item and subitem order after modification

Revision ID: 8d62ca7f6d13
Revises: d659fe1504e7
Create Date: 2024-09-18 18:28:32.238415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d62ca7f6d13'
down_revision: Union[str, None] = 'd659fe1504e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('invoice_subitems', sa.Column('order', sa.Integer(), nullable=True))
    
    # Update existing records in invoice_items
    op.execute("""
    UPDATE invoice_items
    SET "order" = subquery.row_number
    FROM (
        SELECT id, ROW_NUMBER() OVER (PARTITION BY invoice_id ORDER BY id) as row_number
        FROM invoice_items
    ) AS subquery
    WHERE invoice_items.id = subquery.id
    """)
    
    # Update existing records in invoice_subitems
    op.execute("""
    UPDATE invoice_subitems
    SET "order" = subquery.row_number
    FROM (
        SELECT id, ROW_NUMBER() OVER (PARTITION BY invoice_item_id ORDER BY id) as row_number
        FROM invoice_subitems
    ) AS subquery
    WHERE invoice_subitems.id = subquery.id
    """)

    # Alter 'order' column in invoice_items to be non-nullable
    op.alter_column('invoice_items', 'order', nullable=False)
    
    # Alter 'order' column in invoice_subitems to be non-nullable
    op.alter_column('invoice_subitems', 'order', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_subitems', 'order')
    op.drop_column('invoice_items', 'order')
    # ### end Alembic commands ###
