"""Update invoice model with notes field

Revision ID: 94dcc77fa39f
Revises: bcd9b16bcdb3
Create Date: 2024-08-29 21:22:12.062992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94dcc77fa39f'
down_revision: Union[str, None] = 'bcd9b16bcdb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('rate', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('invoice_items', 'amount')
    op.add_column('invoices', sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('manual_total', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('invoices', 'total')
    op.drop_column('invoices', 'tax')
    op.drop_column('invoices', 'subtotal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'manual_total')
    op.drop_column('invoices', 'tax_rate')
    op.add_column('invoice_items', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('invoice_items', 'rate')
    # ### end Alembic commands ###
