"""Enhance logging and exception handling for invoice and template creation

Revision ID: 98dc8ccc3ff0
Revises: 85f3bd0b1a5a
Create Date: 2024-08-31 14:42:22.555919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98dc8ccc3ff0'
down_revision: Union[str, None] = '85f3bd0b1a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
