"""Update contact model with nullable fields and notes

Revision ID: ac95495a34fb
Revises: 4ddec9156356
Create Date: 2024-08-29 17:11:59.081082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac95495a34fb'
down_revision: Union[str, None] = '4ddec9156356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('street_address', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('address_line2', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('city', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('state', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('country', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('contacts', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'notes')
    op.drop_column('contacts', 'country')
    op.drop_column('contacts', 'postal_code')
    op.drop_column('contacts', 'state')
    op.drop_column('contacts', 'city')
    op.drop_column('contacts', 'address_line2')
    op.drop_column('contacts', 'street_address')
    # ### end Alembic commands ###
