"""Add subitems and update template model

Revision ID: af2a8445e9b0
Revises: 59c62398c16d
Create Date: 2024-08-31 10:08:04.506698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2a8445e9b0'
down_revision: Union[str, None] = '59c62398c16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('font_family', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('font_size', sa.Integer(), nullable=True))
    op.add_column('templates', sa.Column('primary_color', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('secondary_color', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('custom_css', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'custom_css')
    op.drop_column('templates', 'logo_url')
    op.drop_column('templates', 'secondary_color')
    op.drop_column('templates', 'primary_color')
    op.drop_column('templates', 'font_size')
    op.drop_column('templates', 'font_family')
    # ### end Alembic commands ###
