"""Update contact model with validation logic for phone numbers and email

Revision ID: bcd9b16bcdb3
Revises: ac95495a34fb
Create Date: 2024-08-29 17:19:41.904230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd9b16bcdb3'
down_revision: Union[str, None] = 'ac95495a34fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
