"""Update models and schema to allow negative values

Revision ID: e76457fa71c2
Revises: 8cc8395739e1
Create Date: 2024-09-01 10:43:26.062552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76457fa71c2'
down_revision: Union[str, None] = '8cc8395739e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
