"""Update invoice and template to allow for invoice previews

Revision ID: e8b52d87fe99
Revises: 87a2381747ee
Create Date: 2024-09-06 12:40:24.460737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b52d87fe99'
down_revision: Union[str, None] = '87a2381747ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
